// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package billion.group.wireguard_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is WireGuardFlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class WireGuardFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class InstalledApp (
  val name: String? = null,
  val packageName: String? = null,
  val icon: ByteArray? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): InstalledApp {
      val name = list[0] as String?
      val packageName = list[1] as String?
      val icon = list[2] as ByteArray?
      return InstalledApp(name, packageName, icon)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      name,
      packageName,
      icon,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Stats (
  val rx: Long? = null,
  val tx: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): Stats {
      val rx = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val tx = list[1].let { if (it is Int) it.toLong() else it as Long? }
      return Stats(rx, tx)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      rx,
      tx,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object WireGuardHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstalledApp.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Stats.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InstalledApp -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is Stats -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WireGuardHostApi {
  fun initialize(interfaceName: String, callback: (Result<Unit>) -> Unit)
  fun startVpn(serverAddress: String, wgQuickConfig: String, providerBundleIdentifier: String, callback: (Result<Unit>) -> Unit)
  fun stopVpn(callback: (Result<Unit>) -> Unit)
  fun stage(callback: (Result<String>) -> Unit)
  fun refreshStage(callback: (Result<Unit>) -> Unit)
  fun getStats(tunnelName: String, callback: (Result<Stats>) -> Unit)
  fun getInstalledApplications(callback: (Result<List<InstalledApp?>>) -> Unit)

  companion object {
    /** The codec used by WireGuardHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      WireGuardHostApiCodec
    }
    /** Sets up an instance of `WireGuardHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: WireGuardHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wireguard_flutter.WireGuardHostApi.initialize", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val interfaceNameArg = args[0] as String
            api.initialize(interfaceNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wireguard_flutter.WireGuardHostApi.startVpn", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serverAddressArg = args[0] as String
            val wgQuickConfigArg = args[1] as String
            val providerBundleIdentifierArg = args[2] as String
            api.startVpn(serverAddressArg, wgQuickConfigArg, providerBundleIdentifierArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wireguard_flutter.WireGuardHostApi.stopVpn", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopVpn() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wireguard_flutter.WireGuardHostApi.stage", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stage() { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wireguard_flutter.WireGuardHostApi.refreshStage", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshStage() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wireguard_flutter.WireGuardHostApi.getStats", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tunnelNameArg = args[0] as String
            api.getStats(tunnelNameArg) { result: Result<Stats> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wireguard_flutter.WireGuardHostApi.getInstalledApplications", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInstalledApplications() { result: Result<List<InstalledApp?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
